source 'https://github.com/CocoaPods/Specs.git'

target 'OBFileTransfer', :exclusive => true do
  pod "OBFileTransfer", :path => "../"
  pod "OBLogger"
end

target 'Tests', :exclusive => true do
  pod "OBFileTransfer", :path => "../"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
end
